### ISSUE TITLE
GPU trainings on GCP fail - drivers not mounted to training container

### ISSUE THREAD

**Issue by pskindel** [riseml/riseml#3]
Hello.

I've deployed RiseML on Google Cloud Kubernetes cluster according to your documentation (docs.riseml.com). Firstly, I've used only nodes with CPU and I successfully ran trainings on that. Then I created new cluster with one GPU node and 4 only-CPU nodes, installed RiseML again and unfortunately I am unable to schedule GPU training on that node. The problem is that training container cannot find `libcuda.so.1` :
```
pskindel@ubuntu:~$ riseml logs 1
1.build       | [2018-03-06T10:25:16Z] --> STARTING
1.build       | [2018-03-06T10:25:16Z] Reason: PREPARE
1.build       | [2018-03-06T10:25:16Z] Message: Preparing environment
1.build       | [2018-03-06T10:25:37Z] --> RUNNING
1.build       | [2018-03-06T10:25:38Z] Preparing image for your experiment
1.build       | [2018-03-06T10:25:38Z] Downloading your code
1.build       | [2018-03-06T10:25:40Z] Running install commands...
1.build       | [2018-03-06T10:25:42Z] Step 1/5 : FROM tensorflow/tensorflow:latest-gpu
1.build       | [2018-03-06T10:25:43Z] Pulling from tensorflow/tensorflow
1.build       | [2018-03-06T10:27:07Z]  ---> aebd66be3e22
1.build       | [2018-03-06T10:27:07Z] Step 2/5 : WORKDIR /code
1.build       | [2018-03-06T10:27:07Z]  ---> 2d3690479b22
1.build       | [2018-03-06T10:27:07Z] Removing intermediate container 43c1f948b943
1.build       | [2018-03-06T10:27:07Z] Step 3/5 : COPY riseml_run.sh /riseml_run.sh
1.build       | [2018-03-06T10:27:08Z]  ---> 708cbe74ed88
1.build       | [2018-03-06T10:27:08Z] Removing intermediate container 07fd05b276e6
1.build       | [2018-03-06T10:27:08Z] Step 4/5 : COPY code /code
1.build       | [2018-03-06T10:27:10Z]  ---> 6e0272867e5c
1.build       | [2018-03-06T10:27:10Z] Removing intermediate container bb01f199915b
1.build       | [2018-03-06T10:27:10Z] Step 5/5 : CMD /riseml_run.sh
1.build       | [2018-03-06T10:27:10Z]  ---> Running in 0201e1a1fa97
1.build       | [2018-03-06T10:27:11Z]  ---> a81ab90a7ac8
1.build       | [2018-03-06T10:27:11Z] Removing intermediate container 0201e1a1fa97
1.build       | [2018-03-06T10:27:11Z] Successfully built a81ab90a7ac8
1.build       | [2018-03-06T10:27:11Z] Image size: 3162.51 MB in 20 layers
1.build       | [2018-03-06T10:27:11Z] Storing your image...
1.build       | [2018-03-06T10:27:47Z] ...stored 50%
1.build       | [2018-03-06T10:27:54Z] ...stored 60%
1.build       | [2018-03-06T10:28:03Z] ...stored 70%
1.build       | [2018-03-06T10:28:13Z] ...stored 80%
1.build       | [2018-03-06T10:28:29Z] ...stored 90%
1.build       | [2018-03-06T10:29:02Z] ...stored 100%
1.tensorboard | [2018-03-06T10:29:06Z] --> PENDING
1.tensorboard | [2018-03-06T10:29:06Z] --> STARTING
1.tensorboard | [2018-03-06T10:29:06Z] Reason: PREPARE
1.tensorboard | [2018-03-06T10:29:06Z] Message: Preparing environment
1.build       | [2018-03-06T10:29:06Z] Build process finished.
1.build       | [2018-03-06T10:29:06Z] --> FINISHED
1.build       | [2018-03-06T10:29:06Z] Reason: COMPLETED
1.build       | [2018-03-06T10:29:06Z] Exit Code: 0
1.train       | [2018-03-06T10:29:06Z] --> PENDING
1             | [2018-03-06T10:29:07Z] --> STARTING
1.train       | [2018-03-06T10:29:07Z] --> STARTING
1.train       | [2018-03-06T10:29:07Z] Reason: PREPARE
1.train       | [2018-03-06T10:29:07Z] Message: Preparing environment
1.tensorboard | [2018-03-06T10:30:34Z] --> RUNNING
1.tensorboard | [2018-03-06T10:30:34Z] /usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
1.tensorboard | [2018-03-06T10:30:34Z]   from ._conv import register_converters as _register_converters
1.tensorboard | [2018-03-06T10:30:34Z] TensorBoard 1.6.0 at http://104.199.107.245/tensorboard/admin-lstmimdbgpu-1-tensorboard (Press CTRL+C to quit)
1             | [2018-03-06T10:30:35Z] --> FAILED
1.tensorboard | [2018-03-06T10:30:35Z] --> KILLED
1.tensorboard | [2018-03-06T10:30:35Z] Reason: KILLED
1.train       | [2018-03-06T10:30:35Z] --> FAILED
1.train       | [2018-03-06T10:30:35Z] Reason: ERROR
1.train       | [2018-03-06T10:30:35Z] Message: Command python imdb_reviews_lstm.py return code: 1
1.train       | [2018-03-06T10:30:35Z] Exit Code: 1
1.train       | [2018-03-06T10:30:35Z] Traceback (most recent call last):
1.train       | [2018-03-06T10:30:35Z]   File "imdb_reviews_lstm.py", line 5, in <module>
1.train       | [2018-03-06T10:30:35Z]     import tensorflow as tf
1.train       | [2018-03-06T10:30:35Z]   File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
1.train       | [2018-03-06T10:30:35Z]     from tensorflow.python import *
1.train       | [2018-03-06T10:30:35Z]   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
1.train       | [2018-03-06T10:30:35Z]     from tensorflow.python import pywrap_tensorflow
1.train       | [2018-03-06T10:30:35Z]   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
1.train       | [2018-03-06T10:30:35Z]     raise ImportError(msg)
1.train       | [2018-03-06T10:30:35Z] ImportError: Traceback (most recent call last):
1.train       | [2018-03-06T10:30:35Z]   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
1.train       | [2018-03-06T10:30:35Z]     from tensorflow.python.pywrap_tensorflow_internal import *
1.train       | [2018-03-06T10:30:35Z]   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
1.train       | [2018-03-06T10:30:35Z]     _pywrap_tensorflow_internal = swig_import_helper()
1.train       | [2018-03-06T10:30:35Z]   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
1.train       | [2018-03-06T10:30:35Z]     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
1.train       | [2018-03-06T10:30:35Z] ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
1.train       | [2018-03-06T10:30:35Z]
1.train       | [2018-03-06T10:30:35Z]
1.train       | [2018-03-06T10:30:35Z] Failed to load the native TensorFlow runtime.
1.train       | [2018-03-06T10:30:35Z]
1.train       | [2018-03-06T10:30:35Z] See https://www.tensorflow.org/install/install_sources#common_installation_problems
1.train       | [2018-03-06T10:30:35Z]
1.train       | [2018-03-06T10:30:35Z] for some common reasons and solutions.  Include the entire stack trace
1.train       | [2018-03-06T10:30:35Z] above this error message when asking for help.
pskindel@ubuntu:~$
```

Also `riseml system info -l` shows wrong information about GPU availability:
```
pskindel@ubuntu:~$ riseml system info -l
NODE                                               CPU  MEM    GPU  GPU MEM  NVIDIA DRIVER  KUBELET VERSION  DOCKER VERSION
gke-cicd-carbon-riseml-default-pool-9f277a8e-cl8f  7    25.9   0    0        -              1.9.3-gke.0      17.3.2
gke-cicd-carbon-riseml-gpu-pool-b58d01ed-tdv3      7    25.9   0    0        384.111        1.9.3-gke.0      17.12.1-ce
gke-cicd-carbon-riseml-default-pool-9f277a8e-psj5  7    25.9   0    0        -              1.9.3-gke.0      17.3.2
gke-cicd-carbon-riseml-default-pool-9f277a8e-lxl1  7    25.9   0    0        -              1.9.3-gke.0      17.3.2
gke-cicd-carbon-riseml-default-pool-9f277a8e-8p8v  7    25.9   0    0        -              1.9.3-gke.0      17.3.2
---------------------------------------------------------------------------------------------------------------------------
Total                                              35   129.7  0    0
pskindel@ubuntu:~$
```
I read 'troubleshooting' section of docs, but it didn't help: everything seems ok:
```
piotr_skindel@gke-cicd-carbon-riseml-gpu-pool-b58d01ed-tdv3:~$ ls /var/lib/nvidia-docker/volumes/nvidia_driver/latest
bin  lib  lib64
```
```
pskindel@ubuntu:~$ kubectl describe node gke-cicd-carbon-riseml-gpu-pool-b58d01ed-tdv3 | grep riseml-monitor | awk '{print $2}'
riseml-monitor-9zrzr
pskindel@ubuntu:~$ kubectl logs riseml-monitor-9zrzr -n=riseml | head -n 3
INFO: Docker client version: {'MinAPIVersion': '1.12', 'ApiVersion': '1.35', 'KernelVersion': '4.13.0-1008-gcp', 'Components': [{'Version': '17.12.1-ce', 'Name': 'Engine', 'Details': {'MinAPIVersion': '1.12', 'ApiVersion': '1.35', 'KernelVersion': '4.13.0-1008-gcp', 'BuildTime': '2018-02-27T22:16:13.000000000+00:00', 'Os': 'linux', 'GitCommit': '7390fc6', 'Arch': 'amd64', 'GoVersion': 'go1.9.4', 'Experimental': 'false'}}], 'Os': 'linux', 'GitCommit': '7390fc6', 'Version': '17.12.1-ce', 'Arch': 'amd64', 'GoVersion': 'go1.9.4', 'BuildTime': '2018-02-27T22:16:13.000000000+00:00', 'Platform': {'Name': ''}}
INFO: GPUs: {'/dev/nvidia0': {'serial': '0320617029062', 'handle': <pynvml.LP_struct_c_nvmlDevice_t object at 0x7f7721682510>, 'mem_total': 11995578368, 'bus_id': '0000:00:04.0', 'name': 'Tesla K80', 'minor': 0}}
INFO: Connection attempt to amqp://riseml-rabbitmq
pskindel@ubuntu:~$
```
Further investigation showed that running container manually from docker inside GPU node prints the same error, but running image using `nvidia-docker` works properly. It seems that RiseML somehow does not mount volume to train container with graphics drivers and I don't know why. Interestingly, riseml-monitor working on that node has properly mounted nvidia drivers in `/usr/local/nvidia`.

Might it be some bug in RiseML? Somehow framework didn't define train container with nvidia-driver mount.

This is the riseml.yml which I was using for testing GPU trainings:
```
project: lstm-imdb-gpu
train:
  framework: tensorflow
  resources:
    cpus: 2
    mem: 4096
    gpus: 1
  run: >-
    python imdb_reviews_lstm.py
```

Some dependencies information:

|               | version                                                   |
|---------------|-----------------------------------------------------------|
| RiseML        | 1.1.0                                                     |
| Linux kernel  | 4.13.0-1008-gcp                                           |
| Docker        | 17.3.2 / (17.12.1-ce on GPU node, also tried with 17.3.2) |
| Kubernetes    | v1.9.3-gke.0                                              |
| Helm          | v2.8.1                                                    |
| Nvidia driver | 384.111                                                   |
| Ubuntu        | Ubuntu 16.04.3 LTS                                        |
| GPU           | Tesla K80                                                 |

GPU and drivers seems OK:
```
piotr_skindel@gke-cicd-carbon-riseml-gpu-pool-b58d01ed-tdv3:~$ nvidia-smi
Tue Mar  6 13:18:28 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   29C    P8    29W / 149W |     11MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by martinbeck** [comment]
Hi,
so you installed on GKE? For installing GPU support you rather should follow Google's guide (https://cloud.google.com/kubernetes-engine/docs/concepts/gpus), i.e., to install the nvidia drivers:
```
kubectl create -f https://raw.githubusercontent.com/GoogleCloudPlatform/container-engine-accelerators/k8s-1.9/nvidia-driver-installer/cos/daemonset-preloaded.yaml
```

For RiseML to recognize the GPUs correctly in it's `riseml system info` output, you need to update the `nvidiaDriverDir` in your install config (`riseml-config.yml`):
```
nvidiaDriverDir: /home/kubernetes/bin/nvidia
```

It is *not* necessary to install nvidia-docker1 on GKE. We will update our docs asap (also on how to use nvidia-docker2).

Let me know, if you still have any problems.

**Comment by pskindel** [comment]
Thank you for your support!

Before reading your answer I've noticed, that you've updated docs in this repository, but not on docs.riseml.com . I attempted again to install RiseML, but using instructions provided in this repository. I am now able to run training on GPU 😄 I've installed `nvidia-docker2` and changed default Docker runtime to `nvidia` on GPU node.

Monitor still badly reports GPU status on node, but as I can see in 1.1.0 version of RiseML, it still works using old drivers-binding method. But in `github.com/riseml/monitor` I see a commit which fixes that problem...? It seems like a lot incosistency between components' versions, docs versions...

**Comment by henningpeters** [comment]
Thanks, I just synced the docs with docs.riseml.com

**Comment by martinbeck** [comment]
@pskindel As for the commit you've seen in `github.com/riseml/monitor`: It's still in the `master` branch only, but will be part of our next release, which will (besides other things) fix this GPU monitoring problem with `nividia-docker2`.

**Comment by pskindel** [comment]
@martinbeck Thank you again for your support. Indeed your instructions written above did help - trainings work on GPU as well as monitor correctly recognizes GPUs. Your hints are even better than what I did before with new docs and `nvidia-docker2` thing. Deployment is much simpler and it works on COS instead Ubuntu.
